gui:
  enlargedSideViewLocation: top
  filterMode: fuzzy
  mainPanelSplitMode: vertical
  nerdFontsVersion: "3"
  scrollHeight: 3
  scrollPastBottom: false
  theme:
    selectedLineBgColor:
      - "#e0e0e0"
  showBottomLine: false
  showCommandLog: false
  useHunkModeInStagingView: false
git:
  autoFetch: false
  autoForwardBranches: none
  merging:
    args: --no-ff
  parseEmoji: true
  overrideGpg: true
quitOnTopLevelReturn: true
notARepository: skip
promptToReturnFromSubprocess: false
keybinding:
  stash:
    popStash: p
  files:
    toggleTreeView: t
    viewResetOptions: R
