theme = "light"

[actions.buffer]
click_channel_name = "replace-pane"
click_username = "replace-pane"
message_channel = "replace-pane"
message_user = "replace-pane"

[actions.sidebar]
buffer = "replace-pane"

[font]
family = "JetBrainsMonoNL Nerd Font"
size = 16

[notifications]
connected = { sound = "peck", show_toast = true }
direct_message = { sound = "peck", show_toast = true }
disconnected = { sound = "peck", show_toast = true }
file_transfer_request = { sound = "peck", show_toast = true }
highlight = { sound = "peck", show_toast = true }
monitored_offline = { sound = "peck", show_toast = true }
monitored_online = { sound = "peck", show_toast = true }
reconnected = { sound = "peck", show_toast = true }

[servers.libera]
nickname = "paveloom/libera"
server = "znc.paveloom.dev"
password_file = "/home/paveloom/.config/halloy/password"
dangerously_accept_invalid_certs = true
use_tls = true

[sidebar]
position = "top"
