server {
    listen 127.0.0.1:80;
    server_name qbittorrent.localhost;

    location / {
        proxy_pass http://127.0.0.1:8080;
        include conf.d/arrs/proxy.conf;
    }
}

server {
    listen 127.0.0.1:80;
    server_name prowlarr.localhost;

    location / {
        proxy_pass http://127.0.0.1:9696;
        include conf.d/arrs/proxy.conf;
    }
}

server {
    listen 127.0.0.1:80;
    server_name flaresolverr.localhost;

    location / {
        proxy_pass http://127.0.0.1:8191;
        include conf.d/arrs/proxy.conf;
    }
}

server {
    listen 127.0.0.1:80;
    server_name radarr.localhost;

    location / {
        proxy_pass http://127.0.0.1:7878;
        include conf.d/arrs/proxy.conf;
    }
}

server {
    listen 127.0.0.1:80;
    server_name sonarr.localhost;

    location / {
        proxy_pass http://127.0.0.1:8989;
        include conf.d/arrs/proxy.conf;
    }
}

server {
    listen 127.0.0.1:80;
    server_name whisparr.localhost;

    location / {
        proxy_pass http://127.0.0.1:6969;
        include conf.d/arrs/proxy.conf;
    }
}

server {
    listen 127.0.0.1:80;
    server_name jellyfin.localhost;

    location / {
        proxy_pass http://192.168.0.155:8096;
        include conf.d/arrs/proxy.conf;
    }
}
