server {
    listen 127.0.0.1:80;
    server_name qbittorrent.localhost;

    location / {
        proxy_pass http://127.0.0.1:8080;
        proxy_set_header Host $host;
    }
}

server {
    listen 127.0.0.1:80;
    server_name prowlarr.localhost;

    location / {
        proxy_pass http://127.0.0.1:9696;
        proxy_set_header Host $host;
    }
}

server {
    listen 127.0.0.1:80;
    server_name flaresolverr.localhost;

    location / {
        proxy_pass http://127.0.0.1:8191;
        proxy_set_header Host $host;
    }
}

server {
    listen 127.0.0.1:80;
    server_name radarr.localhost;

    location / {
        proxy_pass http://127.0.0.1:7878;
        proxy_set_header Host $host;
    }
}

server {
    listen 127.0.0.1:80;
    server_name sonarr.localhost;

    location / {
        proxy_pass http://127.0.0.1:8989;
        proxy_set_header Host $host;
    }
}

server {
    listen 127.0.0.1:80;
    server_name whisparr.localhost;

    location / {
        proxy_pass http://127.0.0.1:6969;
        proxy_set_header Host $host;
    }
}
