server {
    listen 443 ssl;
    server_name lan.paveloom.dev;

    ssl_certificate /etc/acme-sh/lan.paveloom.dev_ecc/fullchain.cer;
    ssl_certificate_key /etc/acme-sh/lan.paveloom.dev_ecc/lan.paveloom.dev.key;

    add_header Referrer-Policy "no-referrer" always;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "DENY" always;

    expires 1h;

    gzip on;
    gunzip on;
    gzip_static on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    access_log /var/log/nginx/lan.paveloom.dev.access_log;
    error_log /var/log/nginx/lan.paveloom.dev.error_log info;

    location / {
        root /mnt/nginx/site/public;
        index index.html;
    }
}
