-- Set the color scheme that is generated by `mini.hues` in `colors/custom.lua`
vim.cmd.colorscheme("custom")

-- Set completion options
vim.opt.completeopt = { "fuzzy", "menuone", "noselect", "nosort", "preview" }

-- Use rounded borders on all floating windows
vim.opt.winborder = "rounded"

-- Make searching case insensitive
vim.opt.ignorecase = true
vim.opt.smartcase = true
