DEBUGFLAGS="-ggdb3 -fno-omit-frame-pointer"

CFLAGS="${CFLAGS} ${DEBUGFLAGS}"
CXXFLAGS="${CXXFLAGS} ${DEBUGFLAGS}"
LDFLAGS="${LDFLAGS} ${DEBUGFLAGS}"

FEATURES="${FEATURES} binpkg-dostrip compressdebug splitdebug -nostrip"

# Requires `dev-util/debugedit` to be installed
FEATURES="${FEATURES} installsources"

# Requires `sys-devel/dwz` to be installed
FEATURES="${FEATURES} dedupdebug"
